[package]
name = "snipora"
description = "Snipora is a lightweight, local-first snippet manager for fast capture, simple organization, and quick search, keeping everyday text at your fingertips."
authors = ["snipora"]
homepage = "https://github.com/snipora"
edition = "2021"

[lib]
name = "snipora_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
lto = "thin"
opt-level = "s"
strip = true

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = ["tray-icon", "image-ico", "image-png"] }
tauri-plugin-log = "2.8.0"
tauri-plugin-notification = "2.3.3"
tauri-plugin-autostart = "2.5.1"
tauri-plugin-global-shortcut = "2.3.1"
tauri-plugin-single-instance = "2.4.2"
tauri-plugin-window-state = "2.4.1"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
tokio = { version = "1.52.3", features = ["rt"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "migrate"] }
rust-i18n = "4.0.0"
uuid = { version = "1.23.1", features = ["v7"] }
time = "0.3.47"
arboard = { version =  "3.6.1" }
sys-locale = "0.3.2"
log = "0.4.30"
log-panics = { version =  "2.1.0", features = ["with-backtrace"] }
